osx_image: xcode10.1
language: objective-c
branches:
  only:
    - master
notifications:
  email: false
before_install:
before_install:
  - gem install bundler
  - bundle install
  - bundle exec pod install
script: bundle exec fastlane Ameiurus
