osx_image: xcode10.1
language: objective-c
branches:
  only:
    - master
notifications:
  email: false
before_install:
before_install:
  - gem install bundler
  - brew update
  - bundle install
install: bundle exec pod install --repo-update --silent
script: bundle exec fastlane Ameiurus
